# Generated by Django 5.1 on 2024-09-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_is_published_blog_slug_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
