# Generated by Django 5.1 on 2024-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="загрузите изображение",
                null=True,
                upload_to="blog/photo",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
