# Generated by Django 5.1 on 2024-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date_create",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
