# Generated by Django 5.1 on 2024-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_date_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_create",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
