# Generated by Django 5.1 on 2024-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_date_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_create",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату публикации",
                null=True,
                verbose_name="Дата публикации",
            ),
        ),
    ]
