# Generated by Django 5.1 on 2024-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="загрузите изображение товара",
                null=True,
                upload_to="products/photo",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
