# Generated by Django 5.1 on 2024-10-02 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_version",
                    models.IntegerField(
                        help_text="введите номер версии (целое число)",
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "name_version",
                    models.CharField(
                        help_text="введите название версии",
                        max_length=50,
                        verbose_name="Название версии",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продукта",
            },
        ),
    ]
