# Generated by Django 5.1 on 2024-10-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="name_version",
        ),
        migrations.AddField(
            model_name="version",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="введите название версии",
                max_length=50,
                null=True,
                verbose_name="Название версии",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
    ]
