# Generated by Django 5.1 on 2024-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_version_name_version_name_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="name_version",
        ),
        migrations.AddField(
            model_name="version",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="введите название версии",
                max_length=50,
                null=True,
                verbose_name="Название версии",
            ),
        ),
    ]
