# Generated by Django 4.2.2 on 2024-10-19 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0008_remove_version_name_version_version_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price"),
                "permissions": [
                    ("can_edit_is_published", "изменить статус публикации"),
                    ("can_edit_description", "редактировать описание"),
                    ("can_edit_category", "изменить категорию"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.RemoveField(
            model_name="version",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать запись",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="name_version",
            field=models.CharField(
                blank=True,
                help_text="введите название версии",
                max_length=50,
                null=True,
                verbose_name="Название версии",
            ),
        ),
    ]
