# Generated by Django 4.2.2 on 2024-10-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options_remove_version_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price"),
                "permissions": [
                    ("can_edit_is_published", "can edit is_published"),
                    ("can_edit_description", "can edit description"),
                    ("can_edit_category", "can edit category"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
